name: "Construção de artefato"

on:
  push:
    branches: [ "main", "aula3" ]
  workflow_dispatch:  

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3    

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: khaoxs
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Constroi e envia imagem docker
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: khaoxs/projeto_go:latest, khaoxs/projeto_go:${{ github.sha }}    